---
- hosts: Dev
  gather_facts: no
  tasks:
    - name: Checking the directory
      stat:
        path: /tmp/gamefolder
      register: status
      
    - name: Deleting the Directory
      file:
        path: /tmp/gamefolder
        state: absent
      when: status.stat.exists == true
        
    - name: creating a directory
      file:
        path: /tmp/gamefolder
        state: directory

    - name: copy war file 
      copy: 
        src: "{{ work }}/greenhouse-1.0.0.war"
        dest: "/tmp/gamefolder/greenhouse-1.0.0.war"
        mode: 0777

    - name: executing war
      shell: "cd /tmp/gamefolder/; nohup java -jar greenhouse-1.0.0.war &"
      become: true
